[package]
name = "supercli-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"

[dependencies.supercli-core]
path = ".."

[[bin]]
name = "sealed_envelope"
path = "fuzz_targets/sealed_envelope.rs"
test = false
doc = false

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false

[[bin]]
name = "sealed_envelope_valid"
path = "fuzz_targets/sealed_envelope_valid.rs"
test = false
doc = false

[workspace]
